### ISSUE TITLE
Workshop curriculum

### ISSUE THREAD

**Issue by bradleyboehmke** [uc-python/python-training-cincinnati-insurance#1]
How does the following look for curriculum?  We have this content in various forms, it just needs to get organized.  If we agree with the outline then I can bring together all the notebooks for the sections and then we can divide and concur on edits/updates.

| Day       | Topic                                                                          |     Time      |  
| :--------:| :-----------------------------------------------| :---------: | 
| __Day 1__ | Introductions                                                        |  1:00 - 1:15  |
|           | Python, VS Code, & Notebooks                                  |  1:15 - 1:45  | 
|           | Variables, operators, & types                                      |  1:45 - 2:30 | 
|           | Break                                                                             |  2:30 - 2:45 | 
|           | More operators & conditionals.                                  |  2:45 - 3:30 | 
|           | Data structures                                                            |  3:30 - 4:00 | 
|           | Q\&A                                                                              | 4:00 - 4:30 | 
| __Day 2__ | Introductions                                                        |  1:00 - 1:15  | 
|           | Conditional statements                                               |  1:15 - 2:00  | 
|           | Iteration statements                                                    |  2:00 - 2:30 | 
|           | Break                                                                             |  2:30 - 2:45 | 
|           | Case study                                                                    |  2:45 - 4:00 | 
|           | Q\&A                                                                              | 4:00 - 4:30 | 
| __Day 3__ | Introductions                                                        |  1:00 - 1:15  | 
|           | Writing functions                                                         |   1:15 - 2:00 | 
|           | Packages, libraries & modules                                    |  2:00 - 2:30  | 
|           | Break                                                                             |  2:30 - 2:45 | 
|           | Importing data                                                              |  2:45 - 3:30 | 
|           | Intro to Pandas                                                             |  3:30 - 4:00  | 
|           | Q\&A                                                                              | 3:45 - 4:15 | 
| __Day 4__ | Introductions                                                        |  1:00 - 1:15  | 
|           | Intro to Pandas  (continued)                                        |  1:15 - 2:15  | 
|           | Python from the shell                                                  |  2:15 - 3:00 | 
|           | Case study                                                                   |  3:00 - 3:45 | 
|           | Wrap up / Concluding remarks                                   | 3:50 - 4:00 |

**Comment by eswan18** [comment]
I like this overall. My only suggestions is to move Conditionals and Iteration up to day one and go more quickly through those, since these students are engineers and they'll be very familiar with those concepts from other languages. Waiting until day 3 seems like it would leave them asking questions.

Maybe that means we need to move back Importing Data, which I think would actually make sense – keep all Pandas stuff for the second half of the class except a brief mention of DataFrames in the Data Structures section, while the first half is more about the core Python language.

**Comment by bradleyboehmke** [comment]
> I like this overall. My only suggestions is to move Conditionals and Iteration up to day one and go more quickly through those, since these students are engineers and they'll be very familiar with those concepts from other languages. Waiting until day 3 seems like it would leave them asking questions.
> 
> Maybe that means we need to move back Importing Data, which I think would actually make sense – keep all Pandas stuff for the second half of the class except a brief mention of DataFrames in the Data Structures section, while the first half is more about the core Python language.

I made some updates to the outline. How does this look?  I moved conditionals and iterations to Day 2 and made some slide changes to Day 3 & 4 so we can, hopefully, fit another case study in.  Thoughts?

**Comment by eswan18** [comment]
Looks great! I'm happy with this schedule.

One thing worth mentioning is that "Variables, operators, and types" is basically the content of "Fundamentals" in our Intro class. I'm not sure exactly what you have in mind for "More operators and conditionals" – we may end up being able to fully cover Conditionals in this section, which would free up time on Day 2. But we can figure that out once we get there, and there is plenty more content we could use to fill up any extra time.

**Comment by augustopher** [comment]
Looks good to me. I would just echo the note on the "More operators and conditionals" for Day 1.

**Comment by bradleyboehmke** [comment]
Yeah, "More operators and conditionals" is super clear, isn't it 🙄 .  What I was referring to is this content, which originally came from our Fundamentals content but then expanded on it:

- __Variables, operators & types__: https://bradleyboehmke.github.io/uc-bana-6043/_build/html/01-module/lesson-1b.html
- __More operators & conditionals__: https://bradleyboehmke.github.io/uc-bana-6043/_build/html/01-module/lesson-1c.html

But looking at that closely we could probably fit both of those sections into one that is about an hour-ish. The 2nd one hits on conditionals because in that class we don't talk conditionals until later on; however, we could just remove that part since we'll be following up with a full conditionals module at the end of day 1 or first thing in day 2.

This could probably result in everything moving up a slot, with functions being taught in Day 2 rather than Day 3.  This would allow for either more Pandas content or something else that you think would be good to fit in.

**Comment by jaycunningham-8451** [comment]
Here's a candidate schedule incorporating the above. This gives more time to pandas and the case studies, and a little bit less time to conditional statements (the students shouldn't have any problem with this, I suspect).

* Day 1:
  * Introductions; 15m; 1:00-1:15
  * Python, VS Code, & Notebooks; 30m; 1:15-1:45
  * Variables, operators, types, conditionals; 1h; 1:45-2:45
  * Break: 15m; 2:45-3:00
  * Data structures; 30m; 3:00-3:30
  * Conditional statements; 30m; 3:30-4:00
  * Q&A; 30m; 4:00-4:30

* Day 2:
  * Introductions; 15m; 1:00-1:15
  * Iteration; 45m; 1:00-1:45
  * Writing functions; 45m; 1:45-2:30
  * Break; 15m; 2:30-2:45
  * Case study; 75m; 2:45-4:00
  * Q&A; 30m; 4:00-4:30

* Day 3:
  * Introductions; 15m; 1:00-1:15
  * Packages, libraries, & modules; 60m; 1:15-2:15
  * Importing data; 15m; 2:15-2:30
  * Break; 15m; 2:30-2:45
  * Intro to pandas; 75m; 2:45-4:00
  * Q&A; 30m; 4:00-4:30

* Day 4:
  * Introductions; 15m; 1:00-1:15
  * Advanced pandas; 45m; 1:15-2:00
  * Python from the shell; 45m; 2:00-2:45
  * Case study; 60m; 2:45-3:45
  * Wrap up / Concluding remarks; 15m; 3:45-4:00

**Comment by bradleyboehmke** [comment]
@jaycunningham-8451, your outline looks good.  Now we need to decide who wants to take on the revision of the material.  If we each take 3-4 sections we'll have it covered. Like I said we have all this content in one form or another so its just a matter of polishing and making minor mods to align to this training. 

1. Python, VS Code, & Notebooks ([content](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/01-Python-and-Jupyter.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/01-module/lesson-1a.ipynb))
2. Variables, operators, types ([content](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/02-Fundamentals.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/01-module/lesson-1b.ipynb))
3. Data structures ([content](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/02-Fundamentals.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/01-module/lesson-1d.ipynb))
4. Conditional statements ([content](https://github.com/uc-python/intermediate-python-datasci/blob/master/notebooks/02-Conditionals.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/06-module/lesson-6a.ipynb))
5. Iteration ([content](https://github.com/uc-python/intermediate-python-datasci/blob/master/notebooks/03-Iteration.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/06-module/lesson-6b.ipynb))
6. Writing functions ([content](https://github.com/uc-python/intermediate-python-datasci/blob/master/notebooks/04-Functions.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/06-module/lesson-6c.ipynb))
7. Case study 1 ([content](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/Case-Study.ipynb), [content](https://github.com/uc-python/intermediate-python-datasci/blob/master/notebooks/Case%20Study.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/instructor-material/module-1/lab1.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/instructor-material/module-6/lab/lab6.ipynb))
8. Packages, libraries, & modules ([content](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/03-Packages-Modules-Function.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/02-module/lesson-2a.ipynb))
9. Importing data ([content](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/04-Importing-Data.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/02-module/lesson-2b.ipynb))
10. Intro to pandas 
11. Advanced pandas (this section and the previous can be some combination of notebooks 5-10 [here](https://github.com/uc-python/intro-python-datasci/tree/master/notebooks) and/or the notebooks in modules 3-4 [here](https://github.com/bradleyboehmke/uc-bana-6043/tree/main/book))
12. Python from the shell ([content](https://github.com/uc-python/intermediate-python-datasci/blob/master/notebooks/06-Python_from_the_Shell.ipynb))
13. Case study 2 ([content](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/Case-Study.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/instructor-material/module-3/lab/lab3.ipynb), [content](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/instructor-material/module-4/lab/lab4.ipynb))

**Comment by eswan18** [comment]
Thanks a bunch for linking to the relevant content, Brad. I can take the lead on 1-4 along with putting together a short intro section (though I'll ask you all for a few bullets about yourselves).

I don't recall whether we ever discussed format, but I think for simplicity, we should just keep with the existing style: Jupyter notebooks that we convert to slides with nbconvert. I have some scripts in the other repos that do this conversion and can get those into the new repo along with some docs.

**Comment by eswan18** [comment]
Also, a heads up to everyone:
- I set up branch protection on `main`. I figured we can merge features in there (trunk-based flow) rather than the kind of awkward dance that Brad and I used to do with separate branches for each of us personally.
  - I enabled `git push --force` to override the protection though, so if we really need to get something merged urgently, one of us can force it.
- I have a PR – setting up some automation scripts – that needs approval (#9). Generally PRs won't be time-sensitive but we'll probably want this stuff to be in `main` so that everyone can build their own slides as they go. Whenever someone has a chance to approve, I'll get it merged.

**Comment by augustopher** [comment]
I can take 5-8.

**Comment by cunningjames** [comment]
> I can take 5-8.

I think that leaves me with the rest. That’ll work.

**Comment by eswan18** [comment]
Here's a markdown version of the schedule. I made just a few small changes, mostly because we usually don't start with introductions after the first day. The 12:30-1:00 time slot (before we really "start" for the day) is typically reserved for Q & A and aimless chat anyway, so at 1:00 we can jump right in.

I'll get this agenda into the readme and the intro notebook.

| Day       | Topic                                                                          |     Time      |
| :--------:| :----------------------------------------------------------------------------- | :-----------: |
| __Day 1__ | Introductions                                                                  |  1:00 - 1:15  |
|           | Python, VSCode, & Notebooks                                                    |  1:15 - 1:45  |
|           | Variables, Operators, & Types                                                  |  1:45 - 2:45  |
|           | Break                                                                          |  2:45 - 3:00  |
|           | Data Structures                                                                |  3:00 - 3:30  |
|           | Conditional Statements                                                         |  3:30 - 4:00  |
|           | Q\&A                                                                           |  4:00 - 4:30  |
| __Day 2__ | Q\&A                                                                           | 12:30 - 1:00  |
|           | Iteration                                                                      |  1:00 - 1:45  |
|           | Writing Functions                                                              |  1:45 - 2:30  |
|           | Break                                                                          |  2:30 - 2:45  |
|           | Case Study, pt. 1                                                              |  2:45 - 4:00  |
|           | Case Study Review; Q&A                                                         |  4:00 - 4:30  |
| __Day 3__ | Q\&A                                                                           | 12:30 - 1:00  |
|           | Packages, Libraries, & Modules                                                 |  1:00 - 2:00  |
|           | Importing Data                                                                 |  2:00 - 2:30  |
|           | Break                                                                          |  2:30 - 2:45  |
|           | Intro to Pandas                                                                |  2:45 - 4:00  |
|           | Q\&A                                                                           |  4:00 - 4:30  |
| __Day 4__ | Q\&A                                                                           | 12:30 - 1:00  |
|           | Advanced Pandas                                                                |  1:00 - 1:45  |
|           | Python from the Shell                                                          |  1:45 - 2:30  |
|           | Case Study, pt. 2                                                              |  2:30 - 3:45  |
|           | Case Study Review; Concluding Remarks                                          |  3:45 - 4:30  |

**Comment by eswan18** [comment]
I think we’re pretty well finished with curriculum planning; closing.
